language: node_js
node_js:
 - 10
before_install: 
 - npm install -g mocha
install:
 - git clone $BIKEAPI
script:
 - cd ./bike-api
 - npm install supertest
 - npm install uuid
 - npm install jsonschema
 - npm test
